/**
 * The build, against synthetic Parquet files generated by DuckDB in a temp dir.
 *
 * What is asserted: the normalized names, the unified types, the row counts, that
 * the dropped columns are gone, and that `data_version` is a function of the input
 * rather than of the run.
 */

import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { Db } from './instance.js';
import {
  buildDatabase,
  dataVersionOf,
  planColumns,
  removeStaleBuilds,
  unifyType,
  type SourceColumn,
} from './build.js';
import {
  CANON_ROWS,
  NON_FINITE_ROWS,
  RAW_ROWS,
  RAW_MANUFACTURERS,
  isNullManufacturer,
  manufacturerOf,
  rawManufacturerOf,
  writeFixtureParquet,
} from '../testing/fixture.js';

let dir: string;
let dataDir: string;
let dbPath: string;
let db: Db;
let dataVersion: string;

beforeAll(async () => {
  dir = mkdtempSync(join(tmpdir(), 'mriqc-build-'));
  dataDir = join(dir, 'parquet');
  dbPath = join(dir, 'mriqc.duckdb');
  await writeFixtureParquet(dataDir);
  // The canonical tables come from the fixture's artifacts here: the synthetic
  // observation files carry four metrics per modality and the policies need all
  // 68. The computed path is tested in `canonical.test.ts`, over the hand-built
  // corpus of `testing/canonical-fixture.ts`.
  const result = await buildDatabase({
    dataDir,
    outPath: dbPath,
    log: () => undefined,
    canonicalFromParquet: true,
  });
  dataVersion = result.dataVersion;
  db = new Db(dbPath, 2);
}, 120_000);

afterAll(async () => {
  await db?.close();
  rmSync(dir, { recursive: true, force: true });
});

/** The DuckDB type of one column of one table. */
async function typeOf(table: string, column: string): Promise<string | undefined> {
  const rows = await db.withRead((c) =>
    c.all(`SELECT column_type FROM (DESCRIBE ${table}) WHERE column_name = ?`, [column]),
  );
  return rows[0] === undefined ? undefined : String(rows[0]['column_type']);
}

describe('unifyType', () => {
  it('keeps a type every source agrees on', () => {
    expect(unifyType('efc', new Set(['efc']), new Set(['DOUBLE']))).toBe('DOUBLE');
    expect(unifyType('id', new Set(['_id']), new Set(['VARCHAR']))).toBe('VARCHAR');
  });

  it('unifies an MRIQC count to BIGINT', () => {
    expect(unifyType('size_x', new Set(['size_x']), new Set(['BIGINT', 'DOUBLE']))).toBe('BIGINT');
  });

  it('unifies a bids_meta acquisition numeric to DOUBLE', () => {
    expect(
      unifyType('flip_angle', new Set(['bids_meta.FlipAngle']), new Set(['BIGINT', 'DOUBLE'])),
    ).toBe('DOUBLE');
  });

  it('falls back to VARCHAR when the disagreement is not numeric', () => {
    expect(unifyType('x', new Set(['x']), new Set(['VARCHAR', 'DOUBLE']))).toBe('VARCHAR');
  });
});

describe('planColumns', () => {
  it('refuses two source columns that normalize to the same name', () => {
    const columns: SourceColumn[] = [
      { name: 'bids_meta.EchoTime', type: 'DOUBLE' },
      { name: 'bids_meta.echo_time', type: 'DOUBLE' },
    ];
    expect(() => planColumns(new Map([['raw_bold', columns]]))).toThrow(/both normalize to/);
  });

  it('never plans a dropped column', () => {
    const plan = planColumns(
      new Map([
        [
          'raw_t1w',
          [
            { name: 'bids_meta.Modality__altcase1', type: 'VARCHAR' },
            { name: 'bids_meta.ImageType.value', type: 'VARCHAR' },
            { name: '_id', type: 'VARCHAR' },
          ] as SourceColumn[],
        ],
      ]),
    );
    expect([...plan.keys()]).toEqual(['id']);
  });
});

describe('buildDatabase', () => {
  it('writes the database file and removes the temporary one', () => {
    expect(existsSync(dbPath)).toBe(true);
    expect(existsSync(`${dbPath}.building-${process.pid}`)).toBe(false);
  });

  it('loads every table with the expected row count', async () => {
    const expected: ReadonlyArray<readonly [string, number]> = [
      ['raw_bold', RAW_ROWS],
      ['raw_t1w', RAW_ROWS],
      ['raw_t2w', RAW_ROWS],
      ['canon_bold_k4plus', CANON_ROWS],
      ['canon_t1w_k3pp', CANON_ROWS],
      ['canon_t2w_k3pp', CANON_ROWS],
      ['k4plus_scales', 3],
      ['ratings', 40],
      ['scanners', 25],
      ['meta', 1],
    ];
    for (const [table, n] of expected) {
      const rows = await db.withRead((c) => c.all(`SELECT count(*) AS n FROM ${table}`));
      expect([table, Number(rows[0]?.['n'])]).toEqual([table, n]);
    }
  });

  it('normalizes the dotted source names', async () => {
    const rows = await db.withRead((c) => c.all('DESCRIBE raw_bold'));
    const names = rows.map((r) => String(r['column_name']));
    expect(names).toContain('created_at');
    expect(names).toContain('updated_at');
    expect(names).toContain('id');
    expect(names).toContain('provenance_md5sum');
    expect(names).toContain('provenance_version');
    expect(names).toContain('provenance_settings_fd_thres');
    expect(names).toContain('echo_time');
    expect(names).toContain('manufacturer');
    expect(names).toContain('manufacturers_model_name');
    expect(names).toContain('magnetic_field_strength');
    expect(names).toContain('task_id');
    // Nothing dotted survives.
    expect(names.filter((n) => n.includes('.'))).toEqual([]);
  });

  it('drops the collision column and the exploded ImageType columns', async () => {
    const rows = await db.withRead((c) => c.all('DESCRIBE raw_t1w'));
    const names = rows.map((r) => String(r['column_name']));
    expect(names).not.toContain('modality_altcase1');
    expect(names.some((n) => n.startsWith('image_type'))).toBe(false);
  });

  it('gives the canonical tables the canonical columns', async () => {
    const rows = await db.withRead((c) => c.all('DESCRIBE canon_bold_k4plus'));
    const names = rows.map((r) => String(r['column_name']));
    expect(names).toContain('canonical_policy');
    expect(names).toContain('canonical_group_rows');
    expect(names).toContain('canonical_distinct_vectors');
    expect(names).toContain('canonical_diameter');
    expect(names).toContain('canonical_selection');
    expect(names).toContain('canonical_hmc_mode');

    const t1w = await db.withRead((c) => c.all('DESCRIBE canon_t1w_k3pp'));
    expect(t1w.map((r) => String(r['column_name']))).not.toContain('canonical_hmc_mode');
  });

  it('unifies counts to BIGINT across modalities that disagreed', async () => {
    for (const table of ['raw_bold', 'raw_t1w', 'raw_t2w', 'canon_t1w_k3pp']) {
      expect([table, await typeOf(table, 'size_x')]).toEqual([table, 'BIGINT']);
      expect([table, await typeOf(table, 'summary_bg_n')]).toEqual([table, 'BIGINT']);
    }
  });

  it('unifies acquisition numerics to DOUBLE across modalities that disagreed', async () => {
    for (const table of ['raw_bold', 'raw_t1w', 'raw_t2w']) {
      expect([table, await typeOf(table, 'flip_angle')]).toEqual([table, 'DOUBLE']);
    }
  });

  it('keeps the types that never disagreed', async () => {
    expect(await typeOf('raw_bold', 'echo_time')).toBe('DOUBLE');
    expect(await typeOf('raw_bold', 'magnetic_field_strength')).toBe('DOUBLE');
    expect(await typeOf('raw_bold', 'created_at')).toBe('TIMESTAMP');
    expect(await typeOf('raw_bold', 'id')).toBe('VARCHAR');
    expect(await typeOf('canon_bold_k4plus', 'canonical_group_rows')).toBe('BIGINT');
  });

  it('preserves NaN and Inf in the raw tables rather than nulling them', async () => {
    const rows = await db.withRead((c) =>
      c.all(
        `SELECT count(*) FILTER (WHERE isnan(fd_mean)) AS nans,
                count(*) FILTER (WHERE isinf(fd_mean)) AS infs,
                count(*) FILTER (WHERE fd_mean IS NULL) AS nulls,
                count(*) FILTER (WHERE isfinite(fd_mean)) AS finite
         FROM raw_bold`,
      ),
    );
    expect(Number(rows[0]?.['nans'])).toBe(NON_FINITE_ROWS / 3);
    expect(Number(rows[0]?.['infs'])).toBe(NON_FINITE_ROWS / 3);
    expect(Number(rows[0]?.['nulls'])).toBe(NON_FINITE_ROWS / 3);
    expect(Number(rows[0]?.['finite'])).toBe(RAW_ROWS - NON_FINITE_ROWS);
  });

  it('records the source name and unified type of every column', async () => {
    const rows = await db.withRead((c) =>
      c.all(
        `SELECT source_name, duck_type FROM columns WHERE modality = 'bold' AND "column" = ?`,
        ['echo_time'],
      ),
    );
    expect(rows[0]).toMatchObject({ source_name: 'bids_meta.EchoTime', duck_type: 'DOUBLE' });

    const sizeX = await db.withRead((c) =>
      c.all(`SELECT duck_type FROM columns WHERE modality = 'T1w' AND "column" = 'size_x'`),
    );
    expect(String(sizeX[0]?.['duck_type'])).toBe('BIGINT');

    // Nothing dropped is recorded either.
    const dropped = await db.withRead((c) =>
      c.all(`SELECT count(*) AS n FROM columns WHERE "column" LIKE 'image_type%'`),
    );
    expect(Number(dropped[0]?.['n'])).toBe(0);
  });

  it('canonicalizes the vendor and keeps the uploaded spelling beside it', async () => {
    for (const table of ['raw_bold', 'raw_t1w', 'raw_t2w', 'canon_bold_k4plus']) {
      const rows = await db.withRead((c) =>
        c.all(
          `SELECT manufacturer, manufacturer_raw, count(*) AS n
           FROM ${table} GROUP BY 1, 2 ORDER BY manufacturer NULLS LAST, 2`,
        ),
      );
      const seen = rows.map((r) => [r['manufacturer'], r['manufacturer_raw']]);
      expect([table, seen]).toEqual([
        table,
        [
          ['GE', RAW_MANUFACTURERS[1]],
          ['Philips', RAW_MANUFACTURERS[2]],
          ['Siemens', RAW_MANUFACTURERS[0]],
          [null, null],
        ],
      ]);
    }
  });

  it('counts every row into the vendor the fixture means it to have', async () => {
    const rows = await db.withRead((c) =>
      c.all(`SELECT manufacturer AS m, manufacturer_raw AS r, count(*) AS n FROM raw_bold GROUP BY 1, 2`),
    );
    const counted = new Map(rows.map((r) => [`${String(r['m'])}|${String(r['r'])}`, Number(r['n'])]));
    const expected = new Map<string, number>();
    for (let i = 0; i < RAW_ROWS; i += 1) {
      const key = `${String(manufacturerOf(i))}|${String(rawManufacturerOf(i))}`;
      expected.set(key, (expected.get(key) ?? 0) + 1);
    }
    expect(counted).toEqual(expected);
    expect(counted.get('null|null')).toBe(
      Array.from({ length: RAW_ROWS }, (_, i) => i).filter(isNullManufacturer).length,
    );
  });

  it('records manufacturer_raw as a column of its own with the same source name', async () => {
    const rows = await db.withRead((c) =>
      c.all(
        `SELECT "column", source_name, duck_type FROM columns
         WHERE modality = 'bold' AND "column" IN ('manufacturer', 'manufacturer_raw')
         ORDER BY "column"`,
      ),
    );
    expect(rows.map((r) => [r['column'], r['source_name'], r['duck_type']])).toEqual([
      ['manufacturer', 'bids_meta.Manufacturer', 'VARCHAR'],
      ['manufacturer_raw', 'bids_meta.Manufacturer', 'VARCHAR'],
    ]);
  });

  it('makes a change to the vendor mapping a new data_version', () => {
    const version = (vendors: string): string =>
      dataVersionOf([{ file: 'a.parquet', bytes: 1, mtimeMs: 2 }], ['bold/raw=none'], null, 'views', vendors);
    expect(version('hash-a')).not.toBe(version('hash-b'));
    expect(version('hash-a')).toBe(version('hash-a'));
  });

  it('exposes ratings through a per-md5 view', async () => {
    const rows = await db.withRead((c) =>
      c.all('SELECT count(*) AS groups, sum(n) AS rated FROM ratings_by_md5'),
    );
    expect(Number(rows[0]?.['rated'])).toBe(40);
    expect(Number(rows[0]?.['groups'])).toBeGreaterThan(0);
  });

  it('writes one meta row with the version, the manifest and the policies', async () => {
    const rows = await db.withRead((c) => c.all('SELECT * FROM meta'));
    const row = rows[0] as Record<string, unknown>;
    expect(String(row['data_version'])).toMatch(/^[0-9a-f]{64}$/);
    expect(row['built_at']).toBeInstanceOf(Date);
    const manifest = JSON.parse(String(row['source_manifest'])) as { files: unknown[] };
    expect(manifest.files).toHaveLength(9);
    const policies = JSON.parse(String(row['policies'])) as {
      views: Record<string, Array<{ view: string; policy: string | null }>>;
    };
    expect(policies.views['bold']).toEqual([
      { view: 'raw', policy: null },
      { view: 'k4plus', policy: 'K4+' },
    ]);
    expect(policies.views['T1w']).toEqual([
      { view: 'raw', policy: null },
      { view: 'k3pp', policy: 'K3++' },
    ]);
  });

  it('is idempotent: a second build of the same input has the same data_version', async () => {
    const second = await buildDatabase({
      dataDir,
      outPath: join(dir, 'again.duckdb'),
      log: () => undefined,
      canonicalFromParquet: true,
    });
    expect(second.dataVersion).toBe(dataVersion);
  }, 120_000);

  it('leaves no temporary file behind when it fails mid-build', async () => {
    const brokenDir = join(dir, 'broken-parquet');
    cpSync(dataDir, brokenDir, { recursive: true });
    // Still a file, still stat-able for the manifest, but not Parquet: `describe`
    // throws once the temp database has already been created.
    writeFileSync(join(brokenDir, 'mriqc_api.T2w.parquet'), 'not parquet at all');

    const outDir = join(dir, 'failed-build');
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, 'mriqc.duckdb');

    await expect(
      buildDatabase({
        dataDir: brokenDir,
        outPath,
        log: () => undefined,
        canonicalFromParquet: true,
      }),
    ).rejects.toThrow();

    expect(readdirSync(outDir).filter((f) => f.includes('.building-'))).toEqual([]);
    expect(existsSync(outPath)).toBe(false);
  }, 120_000);

  it('sweeps up a temporary file an earlier run abandoned', () => {
    const outDir = join(dir, 'stale-build');
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, 'mriqc.duckdb');
    writeFileSync(`${outPath}.building-999999`, 'abandoned');
    writeFileSync(`${outPath}.building-999999.wal`, 'abandoned');
    writeFileSync(outPath, 'the real one');

    expect(removeStaleBuilds(outPath).sort()).toEqual([
      'mriqc.duckdb.building-999999',
      'mriqc.duckdb.building-999999.wal',
    ]);
    expect(readdirSync(outDir)).toEqual(['mriqc.duckdb']);
  });

  it('gives a sampled build a different version from a full one', async () => {
    const sampled = await buildDatabase({
      dataDir,
      outPath: join(dir, 'sampled.duckdb'),
      sample: 20,
      log: () => undefined,
      canonicalFromParquet: true,
    });
    expect(sampled.dataVersion).not.toBe(dataVersion);
    expect(sampled.counts.get('raw_bold')).toBe(20);
    expect(sampled.counts.get('canon_bold_k4plus')).toBe(20);
    // The catalog tables are never sampled.
    expect(sampled.counts.get('scanners')).toBe(25);
  }, 120_000);

  it('serves no quarantine view and no quarantine counts from the artifacts', async () => {
    const relations = await db.withRead((c) =>
      c.all(`SELECT table_name FROM information_schema.tables WHERE table_name LIKE 'v_%_all'`),
    );
    expect(relations).toEqual([]);
    const rows = await db.withRead((c) => c.all('SELECT policies FROM meta'));
    const parsed = JSON.parse(String(rows[0]?.['policies'])) as {
      canonicalSource: string;
      policies: Array<{ id: string; version: string; scaleTable: string; quarantinedRows: number | null }>;
    };
    expect(parsed.canonicalSource).toBe('parquet');
    expect(parsed.policies.map((p) => [p.id, p.version, p.scaleTable, p.quarantinedRows])).toEqual([
      ['k4plus_bold', '1', 'scales_k4plus_bold', null],
      ['k3pp_t1w', '1', 'scales_k3pp_t1w', null],
      ['k3pp_t2w', '1', 'scales_k3pp_t2w', null],
    ]);
  });
});
