/**
 * A synthetic MRIQC Parquet directory and the DuckDB file built from it.
 *
 * The fixture is generated by DuckDB itself so the tests exercise the real Parquet
 * reader, the real dotted source names, and the real type disagreement between
 * modalities. Values are deterministic functions of the row index, so a test can
 * recompute every expected quantile, count and bin in TypeScript rather than
 * trusting the query it is testing.
 *
 * Not part of the shipped package: `tsconfig.json` excludes this directory.
 */

import { mkdirSync } from 'node:fs';
import { DuckDBInstance } from '@duckdb/node-api';
import type { Modality } from '@mriqc/shared';
import { buildDatabase, type BuildResult } from '../db/build.js';
import { Db } from '../db/instance.js';

/**
 * Rows in each synthetic raw table. Deliberately more than DuckDB's 2048-row
 * vector size, so anything that reads results chunk by chunk -- the Arrow export --
 * is exercised across a chunk boundary.
 */
export const RAW_ROWS = 3000;

/** Rows whose primary metric is NaN, +Inf or NULL: one of each per 50 rows. */
export const NON_FINITE_ROWS = (RAW_ROWS / 50) * 3;

/** Every other raw row is a canonical representative. */
export const CANON_ROWS = RAW_ROWS / 2;

/** The canonical manufacturers the fixture cycles through, before nulls are punched in. */
export const MANUFACTURERS = ['Siemens', 'GE', 'Philips'] as const;

/**
 * What the fixture actually writes to `bids_meta.Manufacturer`, in the same
 * order: three spellings that the build's vendor normalization
 * (`db/vendors.ts`) must collapse onto {@link MANUFACTURERS} -- case, trailing
 * whitespace and two different legal suffixes. Everything downstream still sees
 * the canonical three, so the aggregate tests read unchanged.
 */
export const RAW_MANUFACTURERS = ['SIEMENS  ', 'GE Healthcare', 'philips medical systems'] as const;

/** Distinct scanner models, chosen to exceed the 50-group cap of `groupedSummary`. */
export const MODEL_COUNT = 60;

/** A row index whose metric value is NaN. */
export const isNaNRow = (i: number): boolean => i % 50 === 7;
/** A row index whose metric value is +Infinity. */
export const isInfRow = (i: number): boolean => i % 50 === 17;
/** A row index whose metric value is NULL. */
export const isNullRow = (i: number): boolean => i % 50 === 27;
/** A row index with no manufacturer at all. */
export const isNullManufacturer = (i: number): boolean => i % 37 === 0;

/** The finite values of the primary metric, in row order: what every aggregate sees. */
export function finiteMetricValues(rows: number = RAW_ROWS, step = 1): number[] {
  const values: number[] = [];
  for (let i = 0; i < rows; i += step) {
    if (isNaNRow(i) || isInfRow(i) || isNullRow(i)) continue;
    values.push(i * 0.5);
  }
  return values;
}

/** Paired test metrics: ties, a noisy linear relationship, and a monotone square. */
export const ANALYSIS_METRICS = ['fwhm_x', 'fwhm_y', 'fwhm_z'] as const;

/** Independent TypeScript oracle for the analysis columns written below. */
export function analysisValues(i: number): [number | null, number | null, number | null] {
  const x = Math.floor(i / 3);
  return [
    i % 50 === 7 ? NaN : i % 50 === 17 ? Infinity : i % 50 === 27 ? null : x,
    i % 50 === 8 ? NaN : i % 50 === 18 ? -Infinity : i % 50 === 28 ? null : 2 * x + (i % 7) / 10,
    i % 50 === 9 ? NaN : i % 50 === 19 ? Infinity : i % 50 === 29 ? null : x * x,
  ];
}

/** The canonical manufacturer of one row, as the build writes it, or null. */
export function manufacturerOf(i: number): string | null {
  return isNullManufacturer(i) ? null : (MANUFACTURERS[i % 3] as string);
}

/** The manufacturer of one row as the fixture Parquet spells it, or null. */
export function rawManufacturerOf(i: number): string | null {
  return isNullManufacturer(i) ? null : (RAW_MANUFACTURERS[i % 3] as string);
}

/** `quantile_cont` as DuckDB computes it: linear interpolation over the sorted values. */
export function quantileCont(sorted: readonly number[], q: number): number {
  if (sorted.length === 0) return Number.NaN;
  const position = q * (sorted.length - 1);
  const lower = Math.floor(position);
  const upper = Math.ceil(position);
  const low = sorted[lower] as number;
  if (lower === upper) return low;
  return low + (position - lower) * ((sorted[upper] as number) - low);
}

/* ------------------------------------------------------------- generation */

/** The metric columns each modality carries, all DOUBLE, all in the authored catalog. */
const METRICS: Readonly<Record<Modality, readonly string[]>> = {
  bold: ['fd_mean', 'efc', 'fber'],
  T1w: ['cjv', 'efc', 'fber', 'qi_1'],
  T2w: ['cjv', 'efc', 'fber', 'qi_1'],
};

/** The metric a test reads when it wants known quantiles. */
export const PRIMARY_METRIC: Readonly<Record<Modality, string>> = {
  bold: 'fd_mean',
  T1w: 'cjv',
  T2w: 'cjv',
};

/**
 * The value expression for the primary metric: a linear ramp with NaN, +Inf and
 * NULL punched into it, so `isfinite` handling is asserted rather than assumed.
 */
const PRIMARY_EXPR =
  `CASE WHEN i % 50 = 7 THEN 'NaN'::DOUBLE` +
  ` WHEN i % 50 = 17 THEN 'Infinity'::DOUBLE` +
  ` WHEN i % 50 = 27 THEN NULL` +
  ` ELSE i * 0.5 END`;

/**
 * The projection for one observation file.
 *
 * `size_x`, `summary_bg_n` and `bids_meta.FlipAngle` are BIGINT for bold and T2w
 * but DOUBLE for T1w, exactly as the real dumps are, so the build's type
 * unification has something to unify.
 */
function observationSelect(modality: Modality, canonical: boolean): string {
  const t1w = modality === 'T1w';
  const int = (expr: string): string => (t1w ? `CAST(${expr} AS DOUBLE)` : `CAST(${expr} AS BIGINT)`);
  const prefix = modality.toLowerCase();

  const parts = [
    `'${prefix}-' || lpad(i::VARCHAR, 4, '0') AS "_id"`,
    `TIMESTAMP '2020-01-01 00:00:00' + INTERVAL (i) DAY AS "_created"`,
    `TIMESTAMP '2021-01-01 00:00:00' + INTERVAL (i) DAY AS "_updated"`,
    `md5('${prefix}' || i::VARCHAR) AS "provenance.md5sum"`,
    `CASE WHEN i % 2 = 0 THEN '22.0.6' ELSE '23.1.0' END AS "provenance.version"`,
    `0.5 AS "provenance.settings.fd_thres"`,
    // The uploaded spellings, not the canonical ones: the build must normalize
    // them (`db/vendors.ts`) and keep the originals in `manufacturer_raw`.
    `CASE WHEN i % 37 = 0 THEN NULL ELSE ['${RAW_MANUFACTURERS.join("','")}'][i % 3 + 1] END AS "bids_meta.Manufacturer"`,
    // Deliberately higher cardinality than the 50-group cap, so the `other` fold
    // has something to fold.
    `'Model-' || lpad((i % ${MODEL_COUNT})::VARCHAR, 2, '0') AS "bids_meta.ManufacturersModelName"`,
    `CAST([1.5, 3.0, 7.0][i % 3 + 1] AS DOUBLE) AS "bids_meta.MagneticFieldStrength"`,
    `'Institute ' || (i % 4)::VARCHAR AS "bids_meta.InstitutionName"`,
    `'Protocol-' || (i % 6)::VARCHAR AS "bids_meta.ProtocolName"`,
    `'task' || (i % 3)::VARCHAR AS "bids_meta.task_id"`,
    `CAST(0.03 + (i % 5) * 0.001 AS DOUBLE) AS "bids_meta.EchoTime"`,
    `CAST(2.0 + (i % 7) * 0.1 AS DOUBLE) AS "bids_meta.RepetitionTime"`,
    `${int('30 + i % 5')} AS "bids_meta.FlipAngle"`,
    `${int('64 + i % 4')} AS "size_x"`,
    `${int('1000 + i')} AS "summary_bg_n"`,
    `CAST(3.0 + (i % 3) * 0.5 AS DOUBLE) AS "spacing_x"`,
    // Distinct hole patterns exercise pairwise deletion and per-metric ranks.
    `CASE WHEN i % 50 = 7 THEN 'NaN'::DOUBLE WHEN i % 50 = 17 THEN 'Infinity'::DOUBLE
      WHEN i % 50 = 27 THEN NULL ELSE floor(i / 3.0) END AS "fwhm_x"`,
    `CASE WHEN i % 50 = 8 THEN 'NaN'::DOUBLE WHEN i % 50 = 18 THEN '-Infinity'::DOUBLE
      WHEN i % 50 = 28 THEN NULL ELSE 2 * floor(i / 3.0) + (i % 7) / 10.0 END AS "fwhm_y"`,
    `CASE WHEN i % 50 = 9 THEN 'NaN'::DOUBLE WHEN i % 50 = 19 THEN 'Infinity'::DOUBLE
      WHEN i % 50 = 29 THEN NULL ELSE pow(floor(i / 3.0), 2) END AS "fwhm_z"`,
    // Both of these must vanish from the built tables.
    `'collision' AS "bids_meta.Modality__altcase1"`,
    `'ORIGINAL' AS "bids_meta.ImageType.value"`,
  ];

  for (const metric of METRICS[modality]) {
    parts.push(
      metric === PRIMARY_METRIC[modality]
        ? `${PRIMARY_EXPR} AS ${JSON.stringify(metric)}`
        : `CAST(i % 13 + 0.25 AS DOUBLE) AS ${JSON.stringify(metric)}`,
    );
  }

  if (canonical) {
    parts.push(
      `'${modality === 'bold' ? 'K4+' : 'K3++'}' AS "canonical_policy"`,
      `CAST(2 + i % 3 AS BIGINT) AS "canonical_group_rows"`,
      `CAST(1 + i % 2 AS BIGINT) AS "canonical_distinct_vectors"`,
      `CAST(i * 0.01 AS DOUBLE) AS "canonical_diameter"`,
      `'medoid' AS "canonical_selection"`,
    );
    if (modality === 'bold') parts.push(`'6dof' AS "canonical_hmc_mode"`);
  }

  return parts.join(',\n  ');
}

const OBSERVATION_FILES: ReadonlyArray<{
  file: string;
  modality: Modality;
  canonical: boolean;
}> = [
  { file: 'mriqc_api.bold.parquet', modality: 'bold', canonical: false },
  { file: 'mriqc_api.bold.K4+.parquet', modality: 'bold', canonical: true },
  { file: 'mriqc_api.T1w.parquet', modality: 'T1w', canonical: false },
  { file: 'mriqc_api.T1w.K3++.parquet', modality: 'T1w', canonical: true },
  { file: 'mriqc_api.T2w.parquet', modality: 'T2w', canonical: false },
  { file: 'mriqc_api.T2w.K3++.parquet', modality: 'T2w', canonical: true },
];

/** Write the nine synthetic Parquet files `buildDatabase` expects into `dir`. */
export async function writeFixtureParquet(dir: string): Promise<void> {
  mkdirSync(dir, { recursive: true });
  const posix = dir.replace(/\\/g, '/');
  const instance = await DuckDBInstance.create(':memory:');
  const connection = await instance.connect();
  try {
    for (const { file, modality, canonical } of OBSERVATION_FILES) {
      // A canonical file holds representatives only: every other raw row.
      const source = canonical
        ? `(SELECT unnest(generate_series(0, ${RAW_ROWS - 1}, 2)) AS i)`
        : `(SELECT unnest(generate_series(0, ${RAW_ROWS - 1})) AS i)`;
      await connection.run(
        `COPY (SELECT\n  ${observationSelect(modality, canonical)}\nFROM ${source})` +
          ` TO '${posix}/${file}' (FORMAT PARQUET)`,
      );
    }

    await connection.run(
      `COPY (SELECT metric, q25, q75, q75 - q25 AS iqr FROM (VALUES
         ('fd_mean', 0.1, 0.4), ('efc', 0.3, 0.9), ('fber', 100.0, 900.0)
       ) AS t(metric, q25, q75)) TO '${posix}/mriqc_api.bold.K4+.scales.parquet' (FORMAT PARQUET)`,
    );

    await connection.run(
      `COPY (SELECT
         'rating-' || i::VARCHAR AS "_id",
         (i % 4 + 1)::VARCHAR AS "rating",
         md5('bold' || (i * 3)::VARCHAR) AS "md5sum",
         'etag-' || i::VARCHAR AS "_etag",
         TIMESTAMP '2022-01-01 00:00:00' + INTERVAL (i) HOUR AS "_updated",
         'comment ' || i::VARCHAR AS "comment",
         TIMESTAMP '2022-01-01 00:00:00' + INTERVAL (i) HOUR AS "_created",
         'rater' || (i % 2)::VARCHAR AS "name"
       FROM (SELECT unnest(generate_series(0, 39)) AS i))
       TO '${posix}/mriqc_api.rating.parquet' (FORMAT PARQUET)`,
    );

    await connection.run(
      `COPY (SELECT
         'scanner-' || i::VARCHAR AS "scanner_id",
         ['${MANUFACTURERS.join("','")}'][i % 3 + 1] AS "Manufacturer",
         'Model-' || (i % 5)::VARCHAR AS "ManufacturersModelName",
         [1.5, 3.0, 7.0][i % 3 + 1]::VARCHAR AS "MagneticFieldStrength",
         'serial-' || i::VARCHAR AS "DeviceSerialNumber",
         'sw-' || (i % 2)::VARCHAR AS "SoftwareVersions",
         CAST(10 + i AS BIGINT) AS "n_records",
         TIMESTAMP '2019-01-01 00:00:00' AS "first_seen",
         TIMESTAMP '2023-01-01 00:00:00' AS "last_seen"
       FROM (SELECT unnest(generate_series(0, 24)) AS i))
       TO '${posix}/scanners.parquet' (FORMAT PARQUET)`,
    );
  } finally {
    connection.closeSync();
    instance.closeSync();
  }
}

/** A built fixture: the Parquet directory, the database file, and an open handle. */
export interface Fixture {
  dataDir: string;
  dbPath: string;
  db: Db;
  result: BuildResult;
  close(): Promise<void>;
}

/**
 * Generate the Parquet files in `dir`, build the database, and open it.
 *
 * `canonicalFromParquet`, because these observation files carry four metrics per
 * modality and the canonicalization policies need all 68: the canonical tables
 * here are the fixture's own canonical Parquet files, as they were before the
 * build learned to compute them. The policies are exercised against their own
 * hand-built corpus in `testing/canonical-fixture.ts` instead.
 */
export async function makeFixture(dir: string): Promise<Fixture> {
  const dataDir = `${dir}/parquet`;
  const dbPath = `${dir}/fixture.duckdb`;
  await writeFixtureParquet(dataDir);
  const result = await buildDatabase({
    dataDir,
    outPath: dbPath,
    log: () => undefined,
    canonicalFromParquet: true,
  });
  const db = new Db(dbPath, 2);
  return {
    dataDir,
    dbPath,
    db,
    result,
    close: () => db.close(),
  };
}
