/**
 * The authored half of the metric catalog: everything that can be known without
 * opening the database. The server completes it at start-up with value lists,
 * date ranges and finite counts (see `docs/backend-graph.md`, "Metric catalog").
 *
 * GENERATED-BY-HAND-CHECKED DATA. Every id below was verified to resolve to a real
 * normalized column in every parquet file backing the modality/view it claims; run
 * `node scripts/verify-catalog-against-parquet.mjs` to re-check against the source
 * data after any edit.
 */

import type {
  AuthoredCatalog,
  ColumnId,
  FieldDef,
  FieldRole,
  MetricDef,
  Modality,
  View,
  ViewDef,
} from '../types.js';
import { CATALOG_VERSION } from '../types.js';

const id = (value: string): ColumnId => value as ColumnId;

/** Every metric the catalog exposes, ordered by family then subfamily then id. */
const METRICS: readonly MetricDef[] = [
  {
    id: id('qi_1'),
    label: 'Quality index 1',
    family: 'Artifacts and Contrast',
    subfamily: 'Artifact detection',
    description: "Mortamet's quality index 1 (Mortamet et al., 2009): the proportion of background voxels whose intensity is corrupted by artifacts, normalized by the number of voxels in the background \"hat\" mask. Near-zero values are better; -1 means the background was empty, as in a skull-stripped image.",
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-qi',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('qi_2'),
    label: 'Quality index 2',
    family: 'Artifacts and Contrast',
    subfamily: 'Artifact detection',
    description: "Mortamet's quality index 2 (Mortamet et al., 2009): how well a centred chi-squared distribution fits the intensity distribution of the non-artifactual background, once the voxels QI1 flagged as artifactual are removed. Lower is better.",
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-qi2',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('cjv'),
    label: 'Coefficient of joint variation',
    shortLabel: 'CJV',
    family: 'Artifacts and Contrast',
    subfamily: 'Global quality',
    description: "Coefficient of joint variation of gray and white matter (Ganzetti et al., 2016): the two tissues' standard deviations summed, over the gap between their means. High values go with heavy head motion and large intensity non-uniformity artifacts, so lower is better.",
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-cjv',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('cnr'),
    label: 'Contrast-to-noise ratio',
    family: 'Artifacts and Contrast',
    subfamily: 'Global quality',
    description: 'Contrast-to-noise ratio (Magnotta & Friedman, 2006): the distance between the gray- and white-matter means, divided by the combined noise of the air, white matter and gray matter. It extends SNR to say how separated the two tissue distributions are; higher is better.',
    higherIsBetter: true,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-cnr',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('efc'),
    label: 'Entropy-focus criterion',
    shortLabel: 'EFC',
    family: 'Artifacts and Contrast',
    subfamily: 'Global quality',
    description: 'Entropy-focus criterion (Atkinson et al., 1997): the Shannon entropy of the voxel intensities, normalized by the maximum entropy so images of different dimensions can be compared. It rises with the ghosting and blurring that head motion induces, so lower is better.',
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-efc',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('fber'),
    label: 'Foreground-background energy ratio',
    shortLabel: 'FBER',
    family: 'Artifacts and Contrast',
    subfamily: 'Global quality',
    description: 'Foreground-background energy ratio (Shehzad et al., 2015): the mean energy of the image values inside the head over the mean energy outside it. Higher is better; -1 means there is no signal outside the head mask at all, as in a skull-stripped dataset.',
    higherIsBetter: true,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-fber',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
    logScale: true,
  },
  {
    id: id('wm2max'),
    label: 'White-matter to max ratio',
    shortLabel: 'WM2max',
    family: 'Artifacts and Contrast',
    subfamily: 'Global quality',
    description: 'White-matter-to-maximum intensity ratio: the median intensity inside the white-matter mask over the far upper tail (99.95th percentile) of the whole intensity distribution, which catches long tails from hyper-intense carotid vessels and fat. Values should sit around 0.6 to 0.8.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-wm2max',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('inu_med'),
    label: 'Intensity non-uniformity Med',
    shortLabel: 'INU median',
    family: 'Artifacts and Contrast',
    subfamily: 'Intensity non-uniformity',
    description: 'Median of the intensity non-uniformity (bias) field that N4ITK estimates (Tustison et al., 2010), summarizing how much the RF field scales the signal across the volume. Values closer to 1.0 are better.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-inu',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('inu_range'),
    label: 'Intensity non-uniformity Range',
    shortLabel: 'INU range',
    family: 'Artifacts and Contrast',
    subfamily: 'Intensity non-uniformity',
    description: 'Spread, minimum to maximum, of the intensity non-uniformity (bias) field that N4ITK estimates (Tustison et al., 2010). A wider range means the RF field is more inhomogeneous across the volume.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-inu',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('fd_mean'),
    label: 'Mean framewise displacement',
    shortLabel: 'FD mean',
    family: 'Motion',
    subfamily: 'Framewise displacement',
    description: 'Mean framewise displacement (Jenkinson et al., 2002; Power et al., 2012): per volume, the absolute translations and rotations relative to the previous volume are summed -- rotations as arc length on a 50 mm sphere -- and that is averaged over the run.',
    unit: 'mm',
    higherIsBetter: false,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-fd',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('fd_num'),
    label: 'Framewise displacement Num',
    shortLabel: 'FD count',
    family: 'Motion',
    subfamily: 'Framewise displacement',
    description: "Number of volumes whose framewise displacement exceeds MRIQC's 0.20 mm threshold (Jenkinson et al., 2002; Power et al., 2012), that is, how many time points were hit by a motion spike.",
    unit: 'count',
    higherIsBetter: false,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-fd',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('fd_perc'),
    label: 'Framewise displacement Percent',
    shortLabel: 'FD percent',
    family: 'Motion',
    subfamily: 'Framewise displacement',
    description: "Share of the run's volumes whose framewise displacement exceeds MRIQC's 0.20 mm threshold (Jenkinson et al., 2002; Power et al., 2012), as a percentage of the full time series.",
    unit: 'percent',
    higherIsBetter: false,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-fd',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('dummy_trs'),
    label: 'Dummy Trs',
    family: 'Motion',
    subfamily: 'Pre-steady-state volumes',
    description: 'Number of volumes at the start of the functional time series that MRIQC identifies as non-steady state, the so-called dummy scans.',
    unit: 'count',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-dummy',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('size_t'),
    label: 'Size T',
    family: 'Resolution',
    subfamily: 'Matrix size',
    description: "Number of volumes in the functional time series. Read from the image header rather than computed as a quality metric, so MRIQC's IQM documentation does not define it.",
    unit: 'count',
    higherIsBetter: null,
    source: 'authored',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('size_x'),
    label: 'Size X',
    family: 'Resolution',
    subfamily: 'Matrix size',
    description: "Number of voxels along the image's first (x) axis. Read from the image header rather than computed as a quality metric, so MRIQC's IQM documentation does not define it.",
    unit: 'count',
    higherIsBetter: null,
    source: 'authored',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('size_y'),
    label: 'Size Y',
    family: 'Resolution',
    subfamily: 'Matrix size',
    description: "Number of voxels along the image's second (y) axis. Read from the image header rather than computed as a quality metric, so MRIQC's IQM documentation does not define it.",
    unit: 'count',
    higherIsBetter: null,
    source: 'authored',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('size_z'),
    label: 'Size Z',
    family: 'Resolution',
    subfamily: 'Matrix size',
    description: "Number of voxels along the image's third (z) axis. Read from the image header rather than computed as a quality metric, so MRIQC's IQM documentation does not define it.",
    unit: 'count',
    higherIsBetter: null,
    source: 'authored',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('fwhm_avg'),
    label: 'Full-width at half maximum Average',
    shortLabel: 'FWHM mean',
    family: 'Resolution',
    subfamily: 'Smoothness',
    description: "Full width at half maximum of the spatial distribution of image intensities, averaged over the three axes, estimated by AFNI's 3dFWHMx Gaussian width filter (Forman et al., 1995). Lower is better; higher values mean a blurrier image.",
    unit: 'voxels',
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-fwhm',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('fwhm_x'),
    label: 'Full-width at half maximum X',
    shortLabel: 'FWHM X',
    family: 'Resolution',
    subfamily: 'Smoothness',
    description: "Full width at half maximum of the spatial distribution of image intensities along the x axis estimated by AFNI's 3dFWHMx Gaussian width filter (Forman et al., 1995). Lower is better; higher values mean a blurrier image.",
    unit: 'voxels',
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-fwhm',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('fwhm_y'),
    label: 'Full-width at half maximum Y',
    shortLabel: 'FWHM Y',
    family: 'Resolution',
    subfamily: 'Smoothness',
    description: "Full width at half maximum of the spatial distribution of image intensities along the y axis estimated by AFNI's 3dFWHMx Gaussian width filter (Forman et al., 1995). Lower is better; higher values mean a blurrier image.",
    unit: 'voxels',
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-fwhm',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('fwhm_z'),
    label: 'Full-width at half maximum Z',
    shortLabel: 'FWHM Z',
    family: 'Resolution',
    subfamily: 'Smoothness',
    description: "Full width at half maximum of the spatial distribution of image intensities along the z axis estimated by AFNI's 3dFWHMx Gaussian width filter (Forman et al., 1995). Lower is better; higher values mean a blurrier image.",
    unit: 'voxels',
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-fwhm',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('spacing_tr'),
    label: 'Spacing TR',
    family: 'Resolution',
    subfamily: 'Voxel spacing',
    description: "Spacing between volumes along the time axis, i.e. the repetition time. Read from the image header rather than computed as a quality metric, so MRIQC's IQM documentation does not define it.",
    higherIsBetter: null,
    source: 'authored',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('spacing_x'),
    label: 'Spacing X',
    family: 'Resolution',
    subfamily: 'Voxel spacing',
    description: "Voxel size along the image's first (x) axis. Read from the image header rather than computed as a quality metric, so MRIQC's IQM documentation does not define it.",
    unit: 'mm',
    higherIsBetter: null,
    source: 'authored',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('spacing_y'),
    label: 'Spacing Y',
    family: 'Resolution',
    subfamily: 'Voxel spacing',
    description: "Voxel size along the image's second (y) axis. Read from the image header rather than computed as a quality metric, so MRIQC's IQM documentation does not define it.",
    unit: 'mm',
    higherIsBetter: null,
    source: 'authored',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('spacing_z'),
    label: 'Spacing Z',
    family: 'Resolution',
    subfamily: 'Voxel spacing',
    description: "Voxel size along the image's third (z) axis. Read from the image header rather than computed as a quality metric, so MRIQC's IQM documentation does not define it.",
    unit: 'mm',
    higherIsBetter: null,
    source: 'authored',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html',
    modalities: ['bold', 'T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('snrd_csf'),
    label: 'Dietrich SNR CSF',
    family: 'Signal Quality',
    subfamily: 'Dietrich SNR',
    description: "Dietrich's signal-to-noise ratio over the cerebrospinal-fluid mask (Dietrich et al., 2007): the mean tissue intensity over the standard deviation of the air around the head, with the correction factor for the Rayleigh distribution of background noise.",
    higherIsBetter: true,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-snrd',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('snrd_gm'),
    label: 'Dietrich SNR Gray matter',
    shortLabel: 'Dietrich SNR GM',
    family: 'Signal Quality',
    subfamily: 'Dietrich SNR',
    description: "Dietrich's signal-to-noise ratio over the gray-matter mask (Dietrich et al., 2007): the mean tissue intensity over the standard deviation of the air around the head, with the correction factor for the Rayleigh distribution of background noise.",
    higherIsBetter: true,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-snrd',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('snrd_total'),
    label: 'Dietrich SNR Total',
    family: 'Signal Quality',
    subfamily: 'Dietrich SNR',
    description: "Dietrich's signal-to-noise ratio over all tissue masks taken together (Dietrich et al., 2007): the mean tissue intensity over the standard deviation of the air around the head, with the correction factor for the Rayleigh distribution of background noise.",
    higherIsBetter: true,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-snrd',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('snrd_wm'),
    label: 'Dietrich SNR White matter',
    shortLabel: 'Dietrich SNR WM',
    family: 'Signal Quality',
    subfamily: 'Dietrich SNR',
    description: "Dietrich's signal-to-noise ratio over the white-matter mask (Dietrich et al., 2007): the mean tissue intensity over the standard deviation of the air around the head, with the correction factor for the Rayleigh distribution of background noise.",
    higherIsBetter: true,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-snrd',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('snr'),
    label: 'Signal-to-noise ratio',
    shortLabel: 'SNR',
    family: 'Signal Quality',
    subfamily: 'Overall SNR',
    description: 'Signal-to-noise ratio of the functional image: the mean intensity of the foreground (the voxels inside the brain mask) divided by its own standard deviation, with a small-sample correction for the number of voxels.',
    higherIsBetter: true,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-snr',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('snr_csf'),
    label: 'Signal-to-noise ratio CSF',
    shortLabel: 'SNR CSF',
    family: 'Signal Quality',
    subfamily: 'Tissue SNR',
    description: 'Signal-to-noise ratio over the cerebrospinal-fluid mask: the mean intensity of the region divided by its own standard deviation, with a small-sample correction for the number of voxels in the mask.',
    higherIsBetter: true,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-snr',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('snr_gm'),
    label: 'Signal-to-noise ratio Gray matter',
    shortLabel: 'SNR GM',
    family: 'Signal Quality',
    subfamily: 'Tissue SNR',
    description: 'Signal-to-noise ratio over the gray-matter mask: the mean intensity of the region divided by its own standard deviation, with a small-sample correction for the number of voxels in the mask.',
    higherIsBetter: true,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-snr',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('snr_total'),
    label: 'Signal-to-noise ratio Total',
    shortLabel: 'SNR total',
    family: 'Signal Quality',
    subfamily: 'Tissue SNR',
    description: 'Signal-to-noise ratio over all tissue masks taken together: the mean intensity of the region divided by its own standard deviation, with a small-sample correction for the number of voxels in the mask.',
    higherIsBetter: true,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-snr',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('snr_wm'),
    label: 'Signal-to-noise ratio White matter',
    shortLabel: 'SNR WM',
    family: 'Signal Quality',
    subfamily: 'Tissue SNR',
    description: 'Signal-to-noise ratio over the white-matter mask: the mean intensity of the region divided by its own standard deviation, with a small-sample correction for the number of voxels in the mask.',
    higherIsBetter: true,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-snr',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_k'),
    label: 'Summary Background K',
    family: 'Signal Summaries',
    subfamily: 'Background',
    description: 'Kurtosis of the intensity distribution, i.e. how heavy its tails are within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_mad'),
    label: 'Summary Background MAD',
    shortLabel: 'background MAD',
    family: 'Signal Summaries',
    subfamily: 'Background',
    description: 'Median absolute deviation of the intensities, a spread measure robust to outliers within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_mean'),
    label: 'Summary Background Mean',
    shortLabel: 'background mean',
    family: 'Signal Summaries',
    subfamily: 'Background',
    description: 'Mean intensity within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_median'),
    label: 'Summary Background Median',
    shortLabel: 'background median',
    family: 'Signal Summaries',
    subfamily: 'Background',
    description: 'Median intensity within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_n'),
    label: 'Summary Background N',
    family: 'Signal Summaries',
    subfamily: 'Background',
    description: 'Number of voxels within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    unit: 'voxels',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_p05'),
    label: 'Summary Background P05',
    shortLabel: 'background P05',
    family: 'Signal Summaries',
    subfamily: 'Background',
    description: '5th percentile of the intensities within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_p95'),
    label: 'Summary Background P95',
    shortLabel: 'background P95',
    family: 'Signal Summaries',
    subfamily: 'Background',
    description: '95th percentile of the intensities within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_stdv'),
    label: 'Summary Background Standard deviation',
    shortLabel: 'background SD',
    family: 'Signal Summaries',
    subfamily: 'Background',
    description: 'Standard deviation of the intensities within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_fg_k'),
    label: 'Summary Foreground K',
    family: 'Signal Summaries',
    subfamily: 'Foreground',
    description: 'Kurtosis of the intensity distribution, i.e. how heavy its tails are within the foreground mask, the voxels inside the brain mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_fg_mad'),
    label: 'Summary Foreground MAD',
    shortLabel: 'foreground MAD',
    family: 'Signal Summaries',
    subfamily: 'Foreground',
    description: 'Median absolute deviation of the intensities, a spread measure robust to outliers within the foreground mask, the voxels inside the brain mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_fg_mean'),
    label: 'Summary Foreground Mean',
    shortLabel: 'foreground mean',
    family: 'Signal Summaries',
    subfamily: 'Foreground',
    description: 'Mean intensity within the foreground mask, the voxels inside the brain mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_fg_median'),
    label: 'Summary Foreground Median',
    shortLabel: 'foreground median',
    family: 'Signal Summaries',
    subfamily: 'Foreground',
    description: 'Median intensity within the foreground mask, the voxels inside the brain mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_fg_n'),
    label: 'Summary Foreground N',
    family: 'Signal Summaries',
    subfamily: 'Foreground',
    description: 'Number of voxels within the foreground mask, the voxels inside the brain mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    unit: 'voxels',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_fg_p05'),
    label: 'Summary Foreground P05',
    shortLabel: 'foreground P05',
    family: 'Signal Summaries',
    subfamily: 'Foreground',
    description: '5th percentile of the intensities within the foreground mask, the voxels inside the brain mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_fg_p95'),
    label: 'Summary Foreground P95',
    shortLabel: 'foreground P95',
    family: 'Signal Summaries',
    subfamily: 'Foreground',
    description: '95th percentile of the intensities within the foreground mask, the voxels inside the brain mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_fg_stdv'),
    label: 'Summary Foreground Standard deviation',
    shortLabel: 'foreground SD',
    family: 'Signal Summaries',
    subfamily: 'Foreground',
    description: 'Standard deviation of the intensities within the foreground mask, the voxels inside the brain mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-summary',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('aor'),
    label: 'AFNI outlier ratio',
    family: 'Temporal Stability',
    subfamily: 'AFNI quality',
    description: "AFNI's outlier ratio: the mean fraction of outlier voxels per functional volume, as counted by AFNI's 3dToutcount over the time series.",
    higherIsBetter: false,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-aor',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('aqi'),
    label: 'AFNI quality index',
    family: 'Temporal Stability',
    subfamily: 'AFNI quality',
    description: "AFNI's quality index, from 3dTqual: for each volume, one minus its Spearman rank correlation with the median volume, averaged over the run. Lower values are better.",
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-aqi',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('dvars_nstd'),
    label: 'DVARS (non-standardized)',
    family: 'Temporal Stability',
    subfamily: 'DVARS',
    description: 'DVARS (Power et al., 2012): the root mean square, across brain voxels, of the intensity change from one volume to the next, computed after motion correction. This is the unstandardized form; intensities are scaled to 1000, so values read as x10 %ΔBOLD change.',
    unit: 'x10 %ΔBOLD',
    higherIsBetter: false,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-dvars',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('dvars_std'),
    label: 'DVARS standardized',
    shortLabel: 'DVARS std',
    family: 'Temporal Stability',
    subfamily: 'DVARS',
    description: 'Standardized DVARS (Nichols, 2013): the Power et al. (2012) frame-to-frame RMS intensity change, divided by the standard deviation of the temporal difference time series so runs can be compared.',
    higherIsBetter: false,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-dvars',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('dvars_vstd'),
    label: 'DVARS voxel-wise standardized',
    shortLabel: 'DVARS vstd',
    family: 'Temporal Stability',
    subfamily: 'DVARS',
    description: "Voxel-wise standardized DVARS (Nichols, 2013): each voxel's temporal difference series is first divided by that voxel's own standard deviation over time, and the RMS across voxels is taken afterwards.",
    higherIsBetter: false,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-dvars',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('gcor'),
    label: 'Global correlation',
    family: 'Temporal Stability',
    subfamily: 'Global signal',
    description: "Global correlation (Saad et al., 2013), via AFNI's @compute_gcor: the average of every unit-variance voxel time series, dotted with itself and divided by the number of voxels. It summarizes how much signal is shared brain-wide; the docs give no single best direction.",
    higherIsBetter: false,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-gcor',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('gsr_x'),
    label: 'Ghost-to-signal ratio X',
    family: 'Temporal Stability',
    subfamily: 'Global signal',
    description: 'Ghost-to-signal ratio along the x phase-encoding axis (Giannelli et al., 2010): the mean intensity of the Nyquist ghost region, built by shifting the brain mask by half the field of view, minus the non-ghost background, over the mean signal in the brain. A value closer to zero is better.',
    higherIsBetter: false,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-gsr',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('gsr_y'),
    label: 'Ghost-to-signal ratio Y',
    family: 'Temporal Stability',
    subfamily: 'Global signal',
    description: 'Ghost-to-signal ratio along the y phase-encoding axis (Giannelli et al., 2010): the mean intensity of the Nyquist ghost region, built by shifting the brain mask by half the field of view, minus the non-ghost background, over the mean signal in the brain. A value closer to zero is better.',
    higherIsBetter: false,
    directionSource: 'convention',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-gsr',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('tsnr'),
    label: 'Temporal SNR',
    shortLabel: 'tSNR',
    family: 'Temporal Stability',
    subfamily: 'Temporal SNR',
    description: 'Temporal signal-to-noise ratio (Krüger et al., 2001): the median of the voxelwise map of mean BOLD signal over its temporal standard deviation, so it reports how stable the signal is across time. Higher is better.',
    higherIsBetter: true,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-tsnr',
    modalities: ['bold'],
    clipDefault: 'p01p99',
  },
  {
    id: id('icvs_csf'),
    label: 'Intracranial volume fraction CSF',
    shortLabel: 'ICV CSF',
    family: 'Tissue Composition',
    subfamily: 'Intracranial volume fractions',
    description: 'Intracranial volume fraction of cerebrospinal fluid: its partial-volume probabilities summed over all brain voxels. There is no single best value -- the docs say only that it should move within a normative range.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-icvs',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('icvs_gm'),
    label: 'Intracranial volume fraction Gray matter',
    shortLabel: 'ICV GM',
    family: 'Tissue Composition',
    subfamily: 'Intracranial volume fractions',
    description: 'Intracranial volume fraction of gray matter: its partial-volume probabilities summed over all brain voxels. There is no single best value -- the docs say only that it should move within a normative range.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-icvs',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('icvs_wm'),
    label: 'Intracranial volume fraction White matter',
    shortLabel: 'ICV WM',
    family: 'Tissue Composition',
    subfamily: 'Intracranial volume fractions',
    description: 'Intracranial volume fraction of white matter: its partial-volume probabilities summed over all brain voxels. There is no single best value -- the docs say only that it should move within a normative range.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-icvs',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('rpve_csf'),
    label: 'Residual partial volume error CSF',
    shortLabel: 'rPVE CSF',
    family: 'Tissue Composition',
    subfamily: 'Partial volume error',
    description: "Residual partial-volume error for cerebrospinal fluid: how much of the tissue's partial-volume map sits away from a confident 0 or 1, that is, how much of the segmentation is left ambiguous between tissues. Lower is better.",
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-rpve',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('rpve_gm'),
    label: 'Residual partial volume error Gray matter',
    shortLabel: 'rPVE GM',
    family: 'Tissue Composition',
    subfamily: 'Partial volume error',
    description: "Residual partial-volume error for gray matter: how much of the tissue's partial-volume map sits away from a confident 0 or 1, that is, how much of the segmentation is left ambiguous between tissues. Lower is better.",
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-rpve',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('rpve_wm'),
    label: 'Residual partial volume error White matter',
    shortLabel: 'rPVE WM',
    family: 'Tissue Composition',
    subfamily: 'Partial volume error',
    description: "Residual partial-volume error for white matter: how much of the tissue's partial-volume map sits away from a confident 0 or 1, that is, how much of the segmentation is left ambiguous between tissues. Lower is better.",
    higherIsBetter: false,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-rpve',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('tpm_overlap_csf'),
    label: 'TPM overlap Overlap CSF',
    shortLabel: 'TPM overlap CSF',
    family: 'Tissue Composition',
    subfamily: 'TPM overlap',
    description: 'Jaccard overlap between the cerebrospinal fluid tissue probability map estimated from the image and the matching map of the ICBM nonlinear-asymmetric 2009c template, so it reports how well the segmentation lines up with reference anatomy. Higher is better.',
    higherIsBetter: true,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-tpm',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('tpm_overlap_gm'),
    label: 'TPM overlap Overlap Gray matter',
    shortLabel: 'TPM overlap GM',
    family: 'Tissue Composition',
    subfamily: 'TPM overlap',
    description: 'Jaccard overlap between the gray matter tissue probability map estimated from the image and the matching map of the ICBM nonlinear-asymmetric 2009c template, so it reports how well the segmentation lines up with reference anatomy. Higher is better.',
    higherIsBetter: true,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-tpm',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('tpm_overlap_wm'),
    label: 'TPM overlap Overlap White matter',
    shortLabel: 'TPM overlap WM',
    family: 'Tissue Composition',
    subfamily: 'TPM overlap',
    description: 'Jaccard overlap between the white matter tissue probability map estimated from the image and the matching map of the ICBM nonlinear-asymmetric 2009c template, so it reports how well the segmentation lines up with reference anatomy. Higher is better.',
    higherIsBetter: true,
    directionSource: 'mriqc-docs',
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-tpm',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_k'),
    label: 'Summary Background K',
    family: 'Tissue Summaries',
    subfamily: 'Background',
    description: 'Kurtosis of the intensity distribution, i.e. how heavy its tails are within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_mad'),
    label: 'Summary Background MAD',
    shortLabel: 'background MAD',
    family: 'Tissue Summaries',
    subfamily: 'Background',
    description: 'Median absolute deviation of the intensities, a spread measure robust to outliers within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_mean'),
    label: 'Summary Background Mean',
    shortLabel: 'background mean',
    family: 'Tissue Summaries',
    subfamily: 'Background',
    description: 'Mean intensity within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_median'),
    label: 'Summary Background Median',
    shortLabel: 'background median',
    family: 'Tissue Summaries',
    subfamily: 'Background',
    description: 'Median intensity within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_n'),
    label: 'Summary Background N',
    family: 'Tissue Summaries',
    subfamily: 'Background',
    description: 'Number of voxels within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    unit: 'voxels',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_p05'),
    label: 'Summary Background P05',
    shortLabel: 'background P05',
    family: 'Tissue Summaries',
    subfamily: 'Background',
    description: '5th percentile of the intensities within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_p95'),
    label: 'Summary Background P95',
    shortLabel: 'background P95',
    family: 'Tissue Summaries',
    subfamily: 'Background',
    description: '95th percentile of the intensities within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_bg_stdv'),
    label: 'Summary Background Standard deviation',
    shortLabel: 'background SD',
    family: 'Tissue Summaries',
    subfamily: 'Background',
    description: 'Standard deviation of the intensities within the background (air) mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_csf_k'),
    label: 'Summary CSF K',
    family: 'Tissue Summaries',
    subfamily: 'CSF',
    description: 'Kurtosis of the intensity distribution, i.e. how heavy its tails are within the cerebrospinal-fluid partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_csf_mad'),
    label: 'Summary CSF MAD',
    family: 'Tissue Summaries',
    subfamily: 'CSF',
    description: 'Median absolute deviation of the intensities, a spread measure robust to outliers within the cerebrospinal-fluid partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_csf_mean'),
    label: 'Summary CSF Mean',
    family: 'Tissue Summaries',
    subfamily: 'CSF',
    description: 'Mean intensity within the cerebrospinal-fluid partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_csf_median'),
    label: 'Summary CSF Median',
    family: 'Tissue Summaries',
    subfamily: 'CSF',
    description: 'Median intensity within the cerebrospinal-fluid partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_csf_n'),
    label: 'Summary CSF N',
    family: 'Tissue Summaries',
    subfamily: 'CSF',
    description: 'Number of voxels within the cerebrospinal-fluid partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    unit: 'voxels',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_csf_p05'),
    label: 'Summary CSF P05',
    family: 'Tissue Summaries',
    subfamily: 'CSF',
    description: '5th percentile of the intensities within the cerebrospinal-fluid partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_csf_p95'),
    label: 'Summary CSF P95',
    family: 'Tissue Summaries',
    subfamily: 'CSF',
    description: '95th percentile of the intensities within the cerebrospinal-fluid partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_csf_stdv'),
    label: 'Summary CSF Standard deviation',
    shortLabel: 'CSF SD',
    family: 'Tissue Summaries',
    subfamily: 'CSF',
    description: 'Standard deviation of the intensities within the cerebrospinal-fluid partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_gm_k'),
    label: 'Summary Gray matter K',
    shortLabel: 'GM K',
    family: 'Tissue Summaries',
    subfamily: 'Gray matter',
    description: 'Kurtosis of the intensity distribution, i.e. how heavy its tails are within the gray-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_gm_mad'),
    label: 'Summary Gray matter MAD',
    shortLabel: 'GM MAD',
    family: 'Tissue Summaries',
    subfamily: 'Gray matter',
    description: 'Median absolute deviation of the intensities, a spread measure robust to outliers within the gray-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_gm_mean'),
    label: 'Summary Gray matter Mean',
    shortLabel: 'GM mean',
    family: 'Tissue Summaries',
    subfamily: 'Gray matter',
    description: 'Mean intensity within the gray-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_gm_median'),
    label: 'Summary Gray matter Median',
    shortLabel: 'GM median',
    family: 'Tissue Summaries',
    subfamily: 'Gray matter',
    description: 'Median intensity within the gray-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_gm_n'),
    label: 'Summary Gray matter N',
    shortLabel: 'GM N',
    family: 'Tissue Summaries',
    subfamily: 'Gray matter',
    description: 'Number of voxels within the gray-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    unit: 'voxels',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_gm_p05'),
    label: 'Summary Gray matter P05',
    shortLabel: 'GM P05',
    family: 'Tissue Summaries',
    subfamily: 'Gray matter',
    description: '5th percentile of the intensities within the gray-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_gm_p95'),
    label: 'Summary Gray matter P95',
    shortLabel: 'GM P95',
    family: 'Tissue Summaries',
    subfamily: 'Gray matter',
    description: '95th percentile of the intensities within the gray-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_gm_stdv'),
    label: 'Summary Gray matter Standard deviation',
    shortLabel: 'GM SD',
    family: 'Tissue Summaries',
    subfamily: 'Gray matter',
    description: 'Standard deviation of the intensities within the gray-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_wm_k'),
    label: 'Summary White matter K',
    shortLabel: 'WM K',
    family: 'Tissue Summaries',
    subfamily: 'White matter',
    description: 'Kurtosis of the intensity distribution, i.e. how heavy its tails are within the white-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_wm_mad'),
    label: 'Summary White matter MAD',
    shortLabel: 'WM MAD',
    family: 'Tissue Summaries',
    subfamily: 'White matter',
    description: 'Median absolute deviation of the intensities, a spread measure robust to outliers within the white-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_wm_mean'),
    label: 'Summary White matter Mean',
    shortLabel: 'WM mean',
    family: 'Tissue Summaries',
    subfamily: 'White matter',
    description: 'Mean intensity within the white-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_wm_median'),
    label: 'Summary White matter Median',
    shortLabel: 'WM median',
    family: 'Tissue Summaries',
    subfamily: 'White matter',
    description: 'Median intensity within the white-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_wm_n'),
    label: 'Summary White matter N',
    shortLabel: 'WM N',
    family: 'Tissue Summaries',
    subfamily: 'White matter',
    description: 'Number of voxels within the white-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    unit: 'voxels',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_wm_p05'),
    label: 'Summary White matter P05',
    shortLabel: 'WM P05',
    family: 'Tissue Summaries',
    subfamily: 'White matter',
    description: '5th percentile of the intensities within the white-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_wm_p95'),
    label: 'Summary White matter P95',
    shortLabel: 'WM P95',
    family: 'Tissue Summaries',
    subfamily: 'White matter',
    description: '95th percentile of the intensities within the white-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
  {
    id: id('summary_wm_stdv'),
    label: 'Summary White matter Standard deviation',
    shortLabel: 'WM SD',
    family: 'Tissue Summaries',
    subfamily: 'White matter',
    description: 'Standard deviation of the intensities within the white-matter partial-volume mask. One of the per-tissue summary statistics MRIQC reports, each voxel weighted by its partial-volume probability.',
    higherIsBetter: null,
    source: 'mriqc-docs',
    docsUrl: 'https://mriqc.readthedocs.io/en/latest/iqms/t1w.html#iqms-summary',
    modalities: ['T1w', 'T2w'],
    clipDefault: 'p01p99',
  },
];

/**
 * Filterable / groupable / exportable columns that are not metrics.
 *
 * `magnetic_field_strength` is numeric in the source but has a handful of discrete
 * values (1.5, 3, 7), so it is served as a categorical value list.
 */
const FIELDS: readonly FieldDef[] = [
  {
    id: id('manufacturer'),
    label: 'Manufacturer',
    kind: 'categorical',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    // Built, not read: `manufacturer` holds the canonical vendor and this holds
    // the string as the uploader typed it, so every original spelling stays
    // reachable (`packages/server/policies/vendors.csv`). It is not a column of
    // any Parquet file, so `scripts/verify-catalog-against-parquet.mjs` resolves
    // it through its source column, `bids_meta.Manufacturer`.
    id: id('manufacturer_raw'),
    label: 'Manufacturer (as uploaded)',
    kind: 'categorical',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
    // A diagnostic on the vendor mapping, not a filter anyone reaches for:
    // `manufacturer` beside it is the same column with the spellings merged.
    secondary: true,
  },
  {
    id: id('manufacturers_model_name'),
    label: 'Scanner model',
    kind: 'categorical',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('magnetic_field_strength'),
    label: 'Magnetic field strength',
    kind: 'categorical',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('provenance_version'),
    label: 'MRIQC version',
    kind: 'categorical',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('task_id'),
    label: 'Task',
    kind: 'categorical',
    modalities: ['bold'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('institution_name'),
    label: 'Institution',
    kind: 'categorical',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
    // Free text with 200 distinct values at the catalog's ceiling: a long tail,
    // searched when it is wanted rather than scanned in the primary row.
    secondary: true,
  },
  {
    id: id('protocol_name'),
    label: 'Protocol name',
    kind: 'categorical',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
    secondary: true,
  },
  {
    id: id('canonical_hmc_mode'),
    label: 'Motion correction',
    kind: 'categorical',
    modalities: ['bold'],
    filterable: true,
    groupable: true,
    exportable: true,
    // The canonical tables carry it, and so does the canonical-plus-quarantined
    // view, where it is NULL on every quarantined row.
    views: ['k4plus', 'k4plus_all'],
  },
  {
    // Per-group spread under the policy's identity key: how far the admitted
    // group's member vectors sit from their medoid. Only the canonical tables
    // carry it, so it is a canonical-only field (k3pp-structural-canonicalization.md,
    // "Decisions"). DOUBLE in all three canonical Parquet dumps.
    id: id('canonical_diameter'),
    label: 'Run-to-run stability',
    kind: 'numeric',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
    // `k4plus*` only exists for bold and `k3pp*` only for T1w/T2w, so the
    // modality/view cross product already restricts this to the right table.
    views: ['k4plus', 'k3pp', 'k4plus_all', 'k3pp_all'],
  },
  {
    // How many raw uploads collapsed into this canonical row. BIGINT in all
    // three canonical Parquet dumps; canonical-only, like the diameter.
    id: id('canonical_group_rows'),
    label: 'Times uploaded',
    kind: 'numeric',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
    views: ['k4plus', 'k3pp', 'k4plus_all', 'k3pp_all'],
  },
  {
    id: id('created_at'),
    label: 'Upload date',
    kind: 'date',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: false,
    exportable: true,
  },
  {
    id: id('echo_time'),
    label: 'Echo time',
    kind: 'numeric',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('repetition_time'),
    label: 'Repetition time',
    kind: 'numeric',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('spacing_x'),
    label: 'Voxel spacing X',
    kind: 'numeric',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('spacing_y'),
    label: 'Voxel spacing Y',
    kind: 'numeric',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('spacing_z'),
    label: 'Voxel spacing Z',
    kind: 'numeric',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('spacing_tr'),
    label: 'Volume spacing TR',
    kind: 'numeric',
    modalities: ['bold'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('size_x'),
    label: 'Matrix size X',
    kind: 'numeric',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('size_y'),
    label: 'Matrix size Y',
    kind: 'numeric',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('size_z'),
    label: 'Matrix size Z',
    kind: 'numeric',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('size_t'),
    label: 'Matrix size T',
    kind: 'numeric',
    modalities: ['bold'],
    filterable: true,
    groupable: true,
    exportable: true,
  },
  {
    id: id('id'),
    label: 'Record id',
    kind: 'categorical',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: false,
    groupable: false,
    exportable: true,
  },
  {
    id: id('provenance_md5sum'),
    label: 'Source MD5',
    kind: 'categorical',
    modalities: ['bold', 'T1w', 'T2w'],
    filterable: false,
    groupable: false,
    exportable: true,
  },
];

/**
 * The raw log, the canonical policy outputs, and each policy output with its
 * quarantined raw rows added back.
 *
 * The `_all` view is the answer to "and what did the policy throw away": the
 * canonical row per admitted group plus every raw row of every quarantined
 * group, which is the policy's whole corpus with nothing dropped. It carries
 * the same policy id as the canonical-only view -- it is the same policy, shown
 * with its residue -- and is marked `includesQuarantined` so the UI can tell
 * the two apart. Each canonical-only view comes first, which is what
 * {@link canonicalViewFor} picks as a modality's default.
 */
const VIEWS: readonly ViewDef[] = [
  { id: 'raw', label: 'Every upload (raw)', modalities: ['bold', 'T1w', 'T2w'] },
  { id: 'k4plus', label: 'Deduplicated (K4+)', modalities: ['bold'], policy: 'K4+' },
  {
    id: 'k4plus_all',
    label: 'Deduplicated + unstable uploads (K4+)',
    modalities: ['bold'],
    policy: 'K4+',
    includesQuarantined: true,
  },
  { id: 'k3pp', label: 'Deduplicated (K3++)', modalities: ['T1w', 'T2w'], policy: 'K3++' },
  {
    id: 'k3pp_all',
    label: 'Deduplicated + unstable uploads (K3++)',
    modalities: ['T1w', 'T2w'],
    policy: 'K3++',
    includesQuarantined: true,
  },
];

const AUTHORED: AuthoredCatalog = {
  version: CATALOG_VERSION,
  metrics: METRICS,
  fields: FIELDS,
  views: VIEWS,
};

/** The authored catalog. Frozen shape; the server never mutates it. */
export function getAuthoredCatalog(): AuthoredCatalog {
  return AUTHORED;
}

/** Metrics defined for `modality`, in catalog order. */
export function metricsFor(modality: Modality): readonly MetricDef[] {
  return METRICS.filter((m) => m.modalities.includes(modality));
}

function fieldApplies(field: FieldDef, modality: Modality, view: View): boolean {
  if (!field.modalities.includes(modality)) return false;
  return field.views === undefined || field.views.includes(view);
}

function hasRole(field: FieldDef, role: FieldRole): boolean {
  switch (role) {
    case 'filter':
      return field.filterable;
    case 'group':
      return field.groupable;
    case 'export':
      return field.exportable;
  }
}

/** Fields usable as `role` for this modality and view, in catalog order. */
export function fieldsFor(modality: Modality, view: View, role: FieldRole): readonly FieldDef[] {
  return FIELDS.filter((f) => fieldApplies(f, modality, view) && hasRole(f, role));
}

/** True when `metricId` is a metric this modality has. */
export function isValidMetric(modality: Modality, metricId: string): boolean {
  return METRICS.some((m) => m.id === metricId && m.modalities.includes(modality));
}

/** True when `fieldId` is usable as `role` for this modality and view. */
export function isValidField(
  modality: Modality,
  view: View,
  fieldId: string,
  role: FieldRole,
): boolean {
  return FIELDS.some((f) => f.id === fieldId && fieldApplies(f, modality, view) && hasRole(f, role));
}

/** Views defined for `modality`. */
export function viewsFor(modality: Modality): readonly ViewDef[] {
  return VIEWS.filter((v) => v.modalities.includes(modality));
}

/**
 * The view a modality opens on: its canonical policy output, which is `k4plus`
 * for bold and `k3pp` for T1w and T2w.
 *
 * The dashboard's default rather than `raw`, because the canonical table is the
 * one answer to "how many distinct images are there" -- the raw log counts the
 * same image once per upload (`k3pp-structural-canonicalization.md`,
 * "Decisions"). Read off the authored views rather than hard-coded, so a new
 * policy view becomes the default by being authored, and falls back to `raw`
 * for a modality with no canonical view at all. The `_all` views are policy
 * views too, so the default is the first policy view that does *not* carry the
 * quarantined rows: the canonical corpus, not the corpus plus its residue.
 */
export function canonicalViewFor(modality: Modality): View {
  const canonical = viewsFor(modality).find(
    (v) => v.policy !== undefined && v.includesQuarantined !== true,
  );
  return canonical?.id ?? 'raw';
}

/**
 * Every column an export may request for this modality and view: the exportable
 * fields plus every metric of the modality.
 *
 * Deduplicated, because the geometry columns (`size_*`, `spacing_*`) are both
 * metrics and numeric group fields and so appear in each list.
 */
export function exportableColumnsFor(modality: Modality, view: View): readonly ColumnId[] {
  return [
    ...new Set([
      ...fieldsFor(modality, view, 'export').map((f) => f.id),
      ...metricsFor(modality).map((m) => m.id),
    ]),
  ];
}
